### ISSUE TITLE
Service workers not supported 

### ISSUE THREAD

**Issue by perqa** [kiwix/overview#69] opened 2022-07-17 09:31 UTC
I made a zim file of https://ohwhataknight.co.uk/travel-guide-to-pembrokeshire, using https://youzim.it/ on my iPhone.

Trying to open the zim file in Kiwix on iPhone, I get this:

> **Error**
> The requested URL can not be loaded because service workers are not supported here.
> If you use Firefox in Private Mode, try regular mode instead.
> If you use Kiwix-Serve locally, replace the IP in your browser address bar with localhost.

**Comment by kelson42** [comment] 2022-07-17 11:35
Duplicate of https://github.com/openzim/zimit/issues/145

**Closed** 2022-07-17 11:35 UTC
Labels: duplicate, question
