### ISSUE TITLE
iOS Release v 1.11.1 Dark Mode Fix

### ISSUE THREAD

**Issue by smycroft** [kiwix/overview#39] opened 2020-05-08 12:36 UTC
The fix to dark mode has just turned most of the app into "white mode". Pages viewed, etc. are now black text on a white background. Settings menu dark but stored pages "white".

Release on 8 May 2020 on Apple AppStore. This is a NEW release (8/May 2020 TODAY) where the release notes claim [iOS Release v 1.11.1 Dark Mode Fix #244](https://github.com/kiwix/apple/issues/244) is fixed BUT IT IS NOT (so don't blindly close valid reports please!).

The AppStore version number of the fix release is 1.11.1 (can I help it if it's the same version number as the last one!).

If you don't want to sort bugs being reported then I'll give-up trying to help but I'm trying to help here being closed off without anything being checked!

**Comment by kelson42** [comment] 2020-05-08 12:38
duplicate of https://github.com/kiwix/apple/issues/244

**Closed by kelson42** 2020-05-08 12:38 UTC
