### ISSUE TITLE
Add RSS to Kiwix Blog

### ISSUE THREAD

**Issue by imagoiq** [kiwix/overview#55] opened 2021-05-22 16:46 UTC
Hi,

I notice that there is no RSS available (or at least not discoverable) for [Kiwix Blog](https://www.kiwix.org/en/blog/) that would be great to have it and shouldn't require too much effort.

Thanks

**Comment by kelson42** [comment] 2021-05-22 19:04
Duplicate of https://github.com/kiwix/web/issues/118

**Closed** 2021-05-22 19:05 UTC
Labels: duplicate, enhancement
